import type { Metadata } from "next";
import { Istok_Web } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import ProtectedLayout from "@/components/ProtectedLayout";
import ClientWrapper from "@/components/ClientWrapper";

const istokWeb = Istok_Web(
  {
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={istokWeb.className}
      >
        <AuthProvider>
          <ClientWrapper>
            <ProtectedLayout>
              {children}
            </ProtectedLayout>
          </ClientWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
