import type { Metadata } from "next";
import { Istok_Web } from "next/font/google";
import "./globals.css";

const istokWeb = Istok_Web(
  {
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={istokWeb.className}
      >
        {children}
      </body>
    </html>
  );
}
